FROM python:3.12-slim

WORKDIR /app

# Установка зависимостей для psycopg2 и других библиотек
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libpq-dev \
    netcat-traditional \
    gettext \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Установка зависимостей Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

# Копирование проекта
COPY ./app /app/

# Создание непривилегированного пользователя
RUN adduser --disabled-password --gecos '' appuser
RUN chown -R appuser:appuser /app
USER appuser

# Скрипт для ожидания доступности базы данных
COPY ./scripts/entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]